version: '3.3'

volumes:
  db-data:

services:
  

  typebot-viewer:
    image: baptistearno/typebot-viewer:2.22
    ports:
      - '8081:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@clta0qrta00rhp7aufegvp3bm:5432/typebot
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:4000
      # Configurações do Typebot e Google Cloud
      - GOOGLE_CLIENT_ID=http://1057579664250-0qmbhq4tgkfk3u0cteggffamrsuek2ek.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=OqCEOydCqDaVJ2eXw8TQ
      - S3_SECRET_KEY=ViK4TTnGK05LbY2kmbXLmwuW3uYeqtwvMEC9inFh
      - S3_BUCKET=typebot
      - S3_ENDPOINT=db.fluxosmm.com
